// =====================================================
// PRODUCTS — Beyond Bliss Creations
// Source: R K Handicrafts, Saharanpur (supplier)
// Pricing: Option B (shipping baked in, free shipping marketed)
// Generated: 55 products
// Edit prices/dims here. Image URLs from imimg.com (replace with own photos when ready).
// =====================================================

const CATEGORIES = {
  "boxes": "Boxes & Storage",
  "kitchen": "Kitchen & Dining",
  "decor": "Home D\u00e9cor",
  "wellness": "Wellness",
  "furniture": "Statement Pieces"
};

const PRODUCTS = [
  {
    "slug": "wooden-wine-box",
    "name": "Wooden Wine Box",
    "cost": 550,
    "price": 1199,
    "mrp": 1799,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/PE/DS/HS/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "15×6×3 inch",
    "desc": "Premium wooden wine box. 5kg capacity, gift-ready."
  },
  {
    "slug": "wooden-rehal-box",
    "name": "Wooden Rehal Box",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/MX/BY/RH/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Matt finish",
    "desc": "Traditional rehal box for the Holy book."
  },
  {
    "slug": "handcrafted-wooden-box",
    "name": "Handcrafted Wooden Box (Set)",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HO/YM/UI/37510322/new-product-250x250.jpeg",
    "dimensions": "8×5 / 7×5 / 6×4 inch",
    "desc": "Set of hand-carved nesting boxes — three sizes."
  },
  {
    "slug": "hand-carved-wooden-box",
    "name": "Hand Carved Wooden Box",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HQ/JW/OT/37510322/new-product-250x250.jpeg",
    "dimensions": "Handmade",
    "desc": "Intricately hand-carved wooden box. Heirloom quality."
  },
  {
    "slug": "square-jewelry-box",
    "name": "Square Wooden Jewelry Box",
    "cost": 175,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/EW/CE/MI/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "6×6×2 inch",
    "desc": "Square jewellery storage box. 5mm thick walls."
  },
  {
    "slug": "designer-wooden-coin-box",
    "name": "Designer Wooden Coin Box",
    "cost": 140,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/GLADMIN/Default/2020/11/JS/KA/QF/37510322/new-product-250x250.jpeg",
    "dimensions": "Matt finish",
    "desc": "Designer hand-carved coin box. 500g, premium feel."
  },
  {
    "slug": "bottle-shape-coin-box",
    "name": "Bottle Shape Coin Box",
    "cost": 140,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/GLADMIN/Default/2020/11/BH/MX/SG/37510322/new-product-250x250.jpeg",
    "dimensions": "9×4×4 inch",
    "desc": "Unique bottle-shaped wooden coin box. Conversation piece."
  },
  {
    "slug": "wooden-money-box",
    "name": "Wooden Money Box",
    "cost": 110,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/KL/TY/SX/37510322/new-product-250x250.jpeg",
    "dimensions": "6×4 inch",
    "desc": "Rectangular wooden money savings box. Perfect gift for kids."
  },
  {
    "slug": "wooden-money-bank-box",
    "name": "Wooden Money Bank Box (Lockable)",
    "cost": 110,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/AJ/HQ/GV/37510322/new-product-250x250.jpeg",
    "dimensions": "Modern",
    "desc": "Lockable modern wooden money bank — keepsake quality."
  },
  {
    "slug": "modern-wooden-money-bank-box",
    "name": "Modern Money Bank — Round",
    "cost": 110,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/YH/YL/QT/37510322/new-product-250x250.jpeg",
    "dimensions": "4×5 inch · Round",
    "desc": "Round-shaped wooden money bank with modern finish."
  },
  {
    "slug": "wooden-coin-boxes",
    "name": "Wooden Coin Box — Square",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/YB/RH/DT/37510322/new-product-250x250.jpeg",
    "dimensions": "4×4×4 inch",
    "desc": "Square wooden coin storage box. Hand-finished sheesham."
  },
  {
    "slug": "wooden-incense-box",
    "name": "Wooden Incense Box",
    "cost": 85,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/VD/PA/NY/37510322/new-product-250x250.jpeg",
    "dimensions": "3.5×3.5×7 inch",
    "desc": "Matt-finish wooden incense storage box."
  },
  {
    "slug": "rectangle-incense-box",
    "name": "Rectangle Incense Box",
    "cost": 95,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/AX/SY/GQ/37510322/new-product-250x250.jpeg",
    "dimensions": "10.75″×2.5″×1.75″",
    "desc": "Rectangle wooden incense box."
  },
  {
    "slug": "designer-money-bank-box",
    "name": "Designer Money Bank Box",
    "cost": 75,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HS/NN/BG/37510322/new-product-250x250.jpeg",
    "dimensions": "12×15×9 cm",
    "desc": "Compact designer money bank with modern appeal."
  },
  {
    "slug": "wooden-incense-stick-box",
    "name": "Incense Stick Storage Box",
    "cost": 75,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/IE/TU/DI/37510322/new-product-250x250.jpeg",
    "dimensions": "30×5.5×6.2 cm",
    "desc": "Long box for incense sticks (agarbatti). AH0378."
  },
  {
    "slug": "incense-stick-box-modern",
    "name": "Modern Incense Stick Box",
    "cost": 75,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/WI/NY/YG/37510322/new-product-250x250.jpeg",
    "dimensions": "30×5.5×6.5 cm",
    "desc": "Modern wooden incense stick box."
  },
  {
    "slug": "wooden-incense-box-25cm",
    "name": "Compact Incense Box",
    "cost": 70,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/RX/HC/ET/37510322/new-product-250x250.jpeg",
    "dimensions": "25×4.5×5 cm",
    "desc": "Compact wooden incense storage box."
  },
  {
    "slug": "wooden-masala-box",
    "name": "Wooden Masala Box",
    "cost": 380,
    "price": 849,
    "mrp": 1299,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/HR/AN/HY/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Rectangular",
    "desc": "Wooden masala dabba — kitchen essentials storage."
  },
  {
    "slug": "wooden-tray-rect",
    "name": "Wooden Tray (Set)",
    "cost": 390,
    "price": 849,
    "mrp": 1299,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/IA/PF/TD/37510322/new-product-250x250.jpeg",
    "dimensions": "14×10×2 inch",
    "desc": "Rectangular wooden serving tray set."
  },
  {
    "slug": "wooden-rolling-pin-stand",
    "name": "Rolling Pin Stand (Set)",
    "cost": 300,
    "price": 749,
    "mrp": 1149,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/VW/AT/JW/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Kitchen",
    "desc": "Wooden rolling pin display stand. Set."
  },
  {
    "slug": "wooden-spice-jar-tray",
    "name": "Spice Jar Set with Tray",
    "cost": 330,
    "price": 749,
    "mrp": 1149,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/NQ/HE/UM/37510322/new-product-250x250.jpeg",
    "dimensions": "10×1.6 inch · Matte",
    "desc": "Wooden spice jar set with tray. Kitchen showpiece."
  },
  {
    "slug": "sheesham-spice-box",
    "name": "Sheesham Wooden Spice Box",
    "cost": 280,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://4.imimg.com/data4/CM/KO/ANDROID-37510322/product-250x250.jpeg",
    "dimensions": "Plain handmade",
    "desc": "Pure sheesham spice storage box."
  },
  {
    "slug": "rectangle-napkin-holder",
    "name": "Rectangle Napkin Holder",
    "cost": 250,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/LP/DH/LE/37510322/new-product-250x250.jpeg",
    "dimensions": "3×6×10 inch",
    "desc": "Rectangle wooden napkin holder."
  },
  {
    "slug": "wooden-chutney-stand",
    "name": "Wooden Chutney Stand",
    "cost": 245,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/LP/YE/UX/37510322/new-product-250x250.jpeg",
    "dimensions": "14×4.5×5.5 inch",
    "desc": "Wooden + mild steel chutney serving stand."
  },
  {
    "slug": "wooden-tea-coffee-tray",
    "name": "Wooden Tea Coffee Tray",
    "cost": 235,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/SL/OM/SA/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Rectangular · Matte",
    "desc": "Rectangle tea / coffee serving tray."
  },
  {
    "slug": "brown-napkin-holder",
    "name": "Brown Napkin Holder",
    "cost": 210,
    "price": 549,
    "mrp": 849,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/QO/YC/RF/37510322/new-product-250x250.jpeg",
    "dimensions": "Modern",
    "desc": "Modern brown wooden napkin holder."
  },
  {
    "slug": "wooden-napkin-holder",
    "name": "Wooden Napkin Holder",
    "cost": 210,
    "price": 549,
    "mrp": 849,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/AL/EG/JL/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Modern",
    "desc": "Classic wooden napkin holder."
  },
  {
    "slug": "wooden-serving-spoon-set",
    "name": "Wooden Serving Spoon Set",
    "cost": 199,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/VQ/GB/BX/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Multi-size · Boxed",
    "desc": "Premium serving spoon set in 5 sizes."
  },
  {
    "slug": "brown-rolling-pin-set",
    "name": "Rolling Pin Set",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/HW/VF/PJ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Set of 2",
    "desc": "Brown wooden rolling pin set."
  },
  {
    "slug": "wooden-serving-tray-octagonal",
    "name": "Octagonal Serving Tray",
    "cost": 160,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/NM/NT/BP/37510322/new-product-250x250.jpeg",
    "dimensions": "Octagonal · 5mm",
    "desc": "Octagonal wooden serving tray."
  },
  {
    "slug": "wooden-dry-fruit-box",
    "name": "Wooden Dry Fruit Box",
    "cost": 115,
    "price": 349,
    "mrp": 549,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/DW/VH/QU/37510322/new-product-250x250.jpeg",
    "dimensions": "10×8×2 inch",
    "desc": "Wooden + steel dry fruit storage box."
  },
  {
    "slug": "wooden-knife-holder",
    "name": "Wooden Knife Holder",
    "cost": 120,
    "price": 349,
    "mrp": 549,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/12/ZN/PA/YV/37510322/wooden-knife-holder-250x250.jpg",
    "dimensions": "500g",
    "desc": "Solid wooden knife block. Boxed."
  },
  {
    "slug": "wooden-cutlery-set-5",
    "name": "Wooden Cutlery Set (5 pcs)",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/HF/RR/BS/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "12 inch · 5 pieces",
    "desc": "Five-piece wooden cutlery set. Brown finish."
  },
  {
    "slug": "kitchen-serving-tray",
    "name": "Kitchen Serving Tray",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2021/8/NN/PQ/WZ/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Everyday",
    "desc": "Daily-use kitchen serving tray."
  },
  {
    "slug": "wooden-rolling-pin-12b",
    "name": "12-inch Rolling Pin — Premium",
    "cost": 85,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/CR/TR/JQ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "12 inch · Heavier",
    "desc": "Heavier 12-inch wooden belan."
  },
  {
    "slug": "wooden-cutlery-piece",
    "name": "Wooden Cutlery — Single",
    "cost": 80,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/NSDMERP/Default/2021/8/DD/IU/DH/37510322/wooden-cutlery-1629372385614-250x250.jpg",
    "dimensions": "Per piece",
    "desc": "Single wooden cutlery piece. Hand-finished."
  },
  {
    "slug": "wooden-rolling-pin-12",
    "name": "Wooden Rolling Pin — 12\"",
    "cost": 70,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/12/LH/EW/UA/37510322/12-inch-wooden-rolling-pin-250x250.jpg",
    "dimensions": "12 inch",
    "desc": "Classic 12-inch wooden rolling pin (belan)."
  },
  {
    "slug": "brown-cutlery-set-4",
    "name": "Brown Cutlery Set (4 pcs)",
    "cost": 57,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/8/EX/AU/YB/37510322/product-jpeg-250x250.jpg",
    "dimensions": "4 pieces · Boxed",
    "desc": "Four-piece wooden cutlery set. Everyday use."
  },
  {
    "slug": "brown-cutlery-set",
    "name": "Brown Wooden Cutlery Set",
    "cost": 60,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://4.imimg.com/data4/HO/MO/ANDROID-37510322/product-250x250.jpeg",
    "dimensions": "Multi-size",
    "desc": "Wooden cutlery set in multiple sizes."
  },
  {
    "slug": "wooden-bangle-holder",
    "name": "Wooden Bangle Holder",
    "cost": 285,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/GG/SJ/CT/37510322/new-product-250x250.jpeg",
    "dimensions": "27×11×30 cm",
    "desc": "Printed wooden bangle stand. Modern décor."
  },
  {
    "slug": "wooden-tissue-holder-7",
    "name": "Wooden Tissue Holder — 7\"",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/QL/BQ/ST/37510322/new-product-250x250.jpeg",
    "dimensions": "7 inch · Wood + Steel",
    "desc": "Tabletop tissue holder. Wood + mild steel finish."
  },
  {
    "slug": "designer-pen-stand",
    "name": "Designer Pen Stand",
    "cost": 170,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HH/ZL/IB/37510322/new-product-250x250.jpeg",
    "dimensions": "Boxed",
    "desc": "Designer wooden pen stand. Handcraft finish."
  },
  {
    "slug": "wooden-remote-stand",
    "name": "Wooden Remote Stand",
    "cost": 180,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/KI/JE/WJ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "9×17×20 cm · 4 shelves",
    "desc": "4-shelf wooden remote / desk organiser."
  },
  {
    "slug": "wooden-laptop-stand",
    "name": "Wooden Laptop Stand",
    "cost": 145,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/VS/LY/GL/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Foldable",
    "desc": "Portable foldable wooden laptop stand."
  },
  {
    "slug": "wooden-tissue-holder-15cm",
    "name": "Wooden Tissue Holder — Compact",
    "cost": 100,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/TJ/PA/ZN/37510322/new-product-250x250.jpeg",
    "dimensions": "15×6 cm",
    "desc": "Compact wooden tissue holder. Boxed."
  },
  {
    "slug": "wooden-incense-holder",
    "name": "Wooden Incense Holder",
    "cost": 95,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/AU/EN/MM/37510322/new-product-250x250.jpeg",
    "dimensions": "10×10×31 cm",
    "desc": "Tall wooden incense (agarbatti) holder."
  },
  {
    "slug": "brown-incense-holder",
    "name": "Brown Incense Holder",
    "cost": 88,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/LR/IX/KE/37510322/new-product-250x250.jpeg",
    "dimensions": "12×12×31 cm",
    "desc": "Brown wooden incense holder. Wider base."
  },
  {
    "slug": "incense-stick-holder",
    "name": "Incense Stick Holder",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/GY/RE/MA/37510322/new-product-250x250.jpeg",
    "dimensions": "14×14×30 cm",
    "desc": "Wide-base wooden incense stick holder."
  },
  {
    "slug": "wooden-rehal-stand",
    "name": "Wooden Rehal Book Stand",
    "cost": 65,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/CC/KS/LK/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "8 inch · Matt",
    "desc": "Foldable wooden book stand (rehal). 5mm thick."
  },
  {
    "slug": "wooden-pen-stand",
    "name": "Wooden Pen Stand",
    "cost": 60,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/RX/KC/PP/37510322/new-product-250x250.jpeg",
    "dimensions": "Boxed",
    "desc": "Classic wooden pen stand. Desk essential."
  },
  {
    "slug": "wooden-foot-roller",
    "name": "Wooden Foot Roller",
    "cost": 45,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/ZS/II/DP/37510322/new-product-250x250.jpeg",
    "dimensions": "Foot relief",
    "desc": "Wooden foot massage roller. Stress relief."
  },
  {
    "slug": "wooden-massage-roller",
    "name": "Wooden Massage Roller",
    "cost": 65,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/CV/ZL/EO/37510322/new-product-250x250.jpeg",
    "dimensions": "All-purpose",
    "desc": "Wooden massage roller for body."
  },
  {
    "slug": "wooden-body-massage-roller",
    "name": "Wooden Body Massage Roller",
    "cost": 40,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/NG/CW/JI/37510322/new-product-250x250.jpeg",
    "dimensions": "Body relief",
    "desc": "Compact wooden body massage roller."
  },
  {
    "slug": "shoes-wearing-stick",
    "name": "Shoe Horn — Wooden Stick",
    "cost": 35,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/QG/YH/QZ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Long handle",
    "desc": "Long-handle wooden shoe horn / wearing stick."
  },
  {
    "slug": "coffee-tray-stand",
    "name": "Coffee Tray Stand — Premium",
    "cost": 2500,
    "price": 4599,
    "mrp": 6899,
    "discount": 33,
    "category": "furniture",
    "categoryLabel": "Statement Pieces",
    "image": "https://5.imimg.com/data5/GLADMIN/Default/2021/1/BY/LW/BH/37510322/coffee-tray-stand-250x250.jpg",
    "dimensions": "Premium",
    "desc": "Premium coffee tray stand. Statement piece."
  }
];

const inr = (n) => '₹' + n.toLocaleString('en-IN');
