// =====================================================
// PRODUCTS — Beyond Bliss Creations
// Combined R K Handicrafts + Saharanpur PDF catalogue
// Pricing: Option B (shipping baked in, free shipping marketed)
// Generated: 103 products
// =====================================================

const CATEGORIES = {
  "kitchen": "Kitchen & Dining",
  "decor": "Home Décor",
  "boxes": "Boxes & Storage",
  "games": "Games",
  "wellness": "Wellness",
  "furniture": "Statement Pieces"
};

const PRODUCTS = [
  {
    "slug": "serving-redi-trolley",
    "name": "Serving Redi — Trolley Tray",
    "cost": 800,
    "price": 1699,
    "mrp": 2599,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/serving-redi.jpg",
    "dimensions": "Sheesham · Wheels",
    "desc": "Wooden Legacy multi-functional serving redi / decoration trolley for kitchen."
  },
  {
    "slug": "coffee-tray-set-3",
    "name": "Coffee Tray Set (3 sizes)",
    "cost": 680,
    "price": 1449,
    "mrp": 2199,
    "discount": 34,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/coffee-tray-set.jpg",
    "dimensions": "Set of 3 · S/M/L",
    "desc": "Wooden serving trays with handle — set of 3: large, medium, small."
  },
  {
    "slug": "dry-fruit-box-big",
    "name": "Dry Fruit Box — Big (Diwali)",
    "cost": 680,
    "price": 1449,
    "mrp": 2199,
    "discount": 34,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/dry-fruit-box-big.jpg",
    "dimensions": "Large · 4-compartment",
    "desc": "Wooden dry fruit gift box — multipurpose mukhwas / chocolates box for Diwali & festivals."
  },
  {
    "slug": "sugar-coffee-tea-set-3",
    "name": "Sugar–Coffee–Tea Set (3 jars)",
    "cost": 650,
    "price": 1399,
    "mrp": 2099,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/sugar-coffee-tea-set.jpg",
    "dimensions": "3 jars + tray",
    "desc": "Wooden tea, coffee & sugar container set — 3 jars, handles, wooden tray."
  },
  {
    "slug": "square-masala-box-9",
    "name": "Square Masala Box — 9 Compartments",
    "cost": 580,
    "price": 1249,
    "mrp": 1899,
    "discount": 34,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/square-masala-box.jpg",
    "dimensions": "9 sections + spoon",
    "desc": "Sheesham wooden table-top masala dabba. Containers, jars & spoon included."
  },
  {
    "slug": "hexagon-masala-box-6",
    "name": "Hexagon Masala Box (6 sections)",
    "cost": 550,
    "price": 1199,
    "mrp": 1799,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/hexagon-masala-box.jpg",
    "dimensions": "6 compartments + spoon",
    "desc": "Hand-carved wooden hexagon spice box with 6 compartments. Includes lid & spoon."
  },
  {
    "slug": "dry-fruit-tray-big",
    "name": "Dry Fruit Tray — Big (Leaf)",
    "cost": 550,
    "price": 1199,
    "mrp": 1799,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/dry-fruit-tray-big.jpg",
    "dimensions": "Leaf design · Large",
    "desc": "Decorative serving plate tray for dry fruits — large leaf design snack tray."
  },
  {
    "slug": "kettle-coaster-set-6",
    "name": "Kettle Coaster Set (6 pcs)",
    "cost": 450,
    "price": 999,
    "mrp": 1499,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/kettle-coaster.jpg",
    "dimensions": "Set of 6 · Sheesham",
    "desc": "Unique tea coaster set shaped like a kettle. For coffee mugs, tea, water glasses."
  },
  {
    "slug": "cutlery-set-iron-stand",
    "name": "Cutlery Set — Iron Stand",
    "cost": 450,
    "price": 999,
    "mrp": 1499,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/cutlery-set.jpg",
    "dimensions": "3 jars + iron stand",
    "desc": "Wooden cutlery holder for dining table — 3 wooden jars + wrought iron stand."
  },
  {
    "slug": "dry-fruit-box-small",
    "name": "Dry Fruit Box — Small",
    "cost": 450,
    "price": 999,
    "mrp": 1499,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/dry-fruit-box-small.jpg",
    "dimensions": "Small · Compartments",
    "desc": "Multipurpose decorative storage box for nuts & dried fruits. Ideal for gifting."
  },
  {
    "slug": "foldable-apple-basket",
    "name": "Foldable Apple Fruit Basket",
    "cost": 450,
    "price": 999,
    "mrp": 1499,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/wooden-foldable-apple-stand.jpg",
    "dimensions": "Foldable · Carry handle",
    "desc": "Wooden apple-shape foldable fruit basket with carry handle & stand."
  },
  {
    "slug": "duck-coaster-set-6",
    "name": "Duck Coaster Set (6 pcs)",
    "cost": 400,
    "price": 899,
    "mrp": 1399,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/duck-coaster.jpg",
    "dimensions": "Set of 6 · Rosewood",
    "desc": "6 round coasters with decorative duck stand, rosewood with brass inlay."
  },
  {
    "slug": "elephant-coaster-set-6",
    "name": "Elephant Coaster Set (6 pcs)",
    "cost": 420,
    "price": 899,
    "mrp": 1399,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/elephant-coaster.jpg",
    "dimensions": "Set of 6 · Brass",
    "desc": "Wooden handmade tea coasters set of 6, with elephant brass-work stand."
  },
  {
    "slug": "sheesham-single-tray-mandala",
    "name": "Sheesham Single Tray — Mandala",
    "cost": 400,
    "price": 899,
    "mrp": 1399,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/sheshaam-single-tray.jpg",
    "dimensions": "Sheesham · Mandala",
    "desc": "Wood serving tray with engraved mandala design. Rectangular organiser tray."
  },
  {
    "slug": "sheesham-bowls-set-2",
    "name": "Sheesham Bowls (Set of 2)",
    "cost": 400,
    "price": 899,
    "mrp": 1399,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/sheesham-bowls-set-3.jpg",
    "dimensions": "Set of 2 · Sheesham",
    "desc": "Multipurpose round serving bowl set for snacks. Sheesham wood, set of 2."
  },
  {
    "slug": "buckle-tray-papaya",
    "name": "Buckle Tray — Papaya Shape",
    "cost": 400,
    "price": 899,
    "mrp": 1399,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/buckle-tray.jpg",
    "dimensions": "Live edge · Mango",
    "desc": "Beautiful papaya-shape wooden table-décor tray. Live-edge."
  },
  {
    "slug": "wooden-masala-box",
    "name": "Wooden Masala Box",
    "cost": 380,
    "price": 849,
    "mrp": 1299,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/HR/AN/HY/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Rectangular",
    "desc": "Wooden masala dabba — kitchen essentials storage."
  },
  {
    "slug": "wooden-tray-rect",
    "name": "Wooden Tray (Set)",
    "cost": 390,
    "price": 849,
    "mrp": 1299,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/IA/PF/TD/37510322/new-product-250x250.jpeg",
    "dimensions": "14×10×2 inch",
    "desc": "Rectangular wooden serving tray set."
  },
  {
    "slug": "pizza-pan-9",
    "name": "Pizza Pan / Serving Tray (9″)",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/pizza-pan-9.jpg",
    "dimensions": "9″ · Sheesham",
    "desc": "Wooden pizza pan / kitchen platter. Sheesham, 9″ inner, 13″ overall."
  },
  {
    "slug": "wooden-rolling-pin-stand",
    "name": "Rolling Pin Stand (Set)",
    "cost": 300,
    "price": 749,
    "mrp": 1149,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/VW/AT/JW/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Kitchen",
    "desc": "Wooden rolling pin display stand. Set."
  },
  {
    "slug": "wooden-spice-jar-tray",
    "name": "Spice Jar Set with Tray",
    "cost": 330,
    "price": 749,
    "mrp": 1149,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/NQ/HE/UM/37510322/new-product-250x250.jpeg",
    "dimensions": "10×1.6 inch · Matte",
    "desc": "Wooden spice jar set with tray. Kitchen showpiece."
  },
  {
    "slug": "sheesham-spice-box",
    "name": "Sheesham Wooden Spice Box",
    "cost": 280,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://4.imimg.com/data4/CM/KO/ANDROID-37510322/product-250x250.jpeg",
    "dimensions": "Plain handmade",
    "desc": "Pure sheesham spice storage box."
  },
  {
    "slug": "spatula-set-sheesham-5",
    "name": "Spatula Set — Sheesham (5 pcs)",
    "cost": 280,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/spatula-set-sheshaam.jpg",
    "dimensions": "5 pcs · Sheesham",
    "desc": "Pure sheesham wood spoons & spatulas for non-stick cookware. Cooking, baking, mixing."
  },
  {
    "slug": "dry-fruit-tray-small",
    "name": "Dry Fruit Tray — Small (Leaf)",
    "cost": 280,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/dry-fruit-tray-small.jpg",
    "dimensions": "Leaf design · Small",
    "desc": "Decorative serving plate tray for dry fruits. Wooden leaf design."
  },
  {
    "slug": "rectangle-napkin-holder",
    "name": "Rectangle Napkin Holder",
    "cost": 250,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/LP/DH/LE/37510322/new-product-250x250.jpeg",
    "dimensions": "3×6×10 inch",
    "desc": "Rectangle wooden napkin holder."
  },
  {
    "slug": "wooden-chutney-stand",
    "name": "Wooden Chutney Stand",
    "cost": 245,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/LP/YE/UX/37510322/new-product-250x250.jpeg",
    "dimensions": "14×4.5×5.5 inch",
    "desc": "Wooden + mild steel chutney serving stand."
  },
  {
    "slug": "wooden-tea-coffee-tray",
    "name": "Wooden Tea Coffee Tray",
    "cost": 235,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/SL/OM/SA/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Rectangular · Matte",
    "desc": "Rectangle tea / coffee serving tray."
  },
  {
    "slug": "wooden-mug-rustic",
    "name": "Wooden Mug — Rustic",
    "cost": 250,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/mug.jpg",
    "dimensions": "Mango wood",
    "desc": "Handmade wooden mug. Coffee, tea, beer, or decorative use."
  },
  {
    "slug": "spatula-set-natural-5",
    "name": "Spatula Set — Natural (5 pcs)",
    "cost": 230,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/spatula-set.jpg",
    "dimensions": "5 pcs · Mango",
    "desc": "Natural wooden spoons set & spatula for cooking. Non-stick cookware safe."
  },
  {
    "slug": "brown-napkin-holder",
    "name": "Brown Napkin Holder",
    "cost": 210,
    "price": 549,
    "mrp": 849,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/QO/YC/RF/37510322/new-product-250x250.jpeg",
    "dimensions": "Modern",
    "desc": "Modern brown wooden napkin holder."
  },
  {
    "slug": "wooden-napkin-holder",
    "name": "Wooden Napkin Holder",
    "cost": 210,
    "price": 549,
    "mrp": 849,
    "discount": 35,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/AL/EG/JL/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Modern",
    "desc": "Classic wooden napkin holder."
  },
  {
    "slug": "wooden-serving-spoon-set",
    "name": "Wooden Serving Spoon Set",
    "cost": 199,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/VQ/GB/BX/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Multi-size · Boxed",
    "desc": "Premium serving spoon set in 5 sizes."
  },
  {
    "slug": "brown-rolling-pin-set",
    "name": "Rolling Pin Set",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/HW/VF/PJ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Set of 2",
    "desc": "Brown wooden rolling pin set."
  },
  {
    "slug": "barrel-jar-cutlery",
    "name": "Barrel Jar — Cutlery Holder",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/barrel-jar.jpg",
    "dimensions": "Sheesham · Single",
    "desc": "Decorlay wooden barrel-shaped cutlery / spoon / utensils jar (single)."
  },
  {
    "slug": "wooden-serving-tray-octagonal",
    "name": "Octagonal Serving Tray",
    "cost": 160,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/NM/NT/BP/37510322/new-product-250x250.jpeg",
    "dimensions": "Octagonal · 5mm",
    "desc": "Octagonal wooden serving tray."
  },
  {
    "slug": "handmade-spoons-3",
    "name": "Handmade Wooden Spoons (3 pcs)",
    "cost": 150,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "/spoons.jpg",
    "dimensions": "Set of 3 · Sheesham",
    "desc": "Naturally non-stick handmade wooden spoons. Set of 3."
  },
  {
    "slug": "wooden-dry-fruit-box",
    "name": "Wooden Dry Fruit Box",
    "cost": 115,
    "price": 349,
    "mrp": 549,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/DW/VH/QU/37510322/new-product-250x250.jpeg",
    "dimensions": "10×8×2 inch",
    "desc": "Wooden + steel dry fruit storage box."
  },
  {
    "slug": "wooden-knife-holder",
    "name": "Wooden Knife Holder",
    "cost": 120,
    "price": 349,
    "mrp": 549,
    "discount": 36,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/12/ZN/PA/YV/37510322/wooden-knife-holder-250x250.jpg",
    "dimensions": "500g",
    "desc": "Solid wooden knife block. Boxed."
  },
  {
    "slug": "wooden-cutlery-set-5",
    "name": "Wooden Cutlery Set (5 pcs)",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/HF/RR/BS/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "12 inch · 5 pieces",
    "desc": "Five-piece wooden cutlery set. Brown finish."
  },
  {
    "slug": "kitchen-serving-tray",
    "name": "Kitchen Serving Tray",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2021/8/NN/PQ/WZ/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Everyday",
    "desc": "Daily-use kitchen serving tray."
  },
  {
    "slug": "wooden-rolling-pin-12b",
    "name": "12-inch Rolling Pin — Premium",
    "cost": 85,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/CR/TR/JQ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "12 inch · Heavier",
    "desc": "Heavier 12-inch wooden belan."
  },
  {
    "slug": "wooden-cutlery-piece",
    "name": "Wooden Cutlery — Single",
    "cost": 80,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/NSDMERP/Default/2021/8/DD/IU/DH/37510322/wooden-cutlery-1629372385614-250x250.jpg",
    "dimensions": "Per piece",
    "desc": "Single wooden cutlery piece. Hand-finished."
  },
  {
    "slug": "wooden-rolling-pin-12",
    "name": "Wooden Rolling Pin — 12\"",
    "cost": 70,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/12/LH/EW/UA/37510322/12-inch-wooden-rolling-pin-250x250.jpg",
    "dimensions": "12 inch",
    "desc": "Classic 12-inch wooden rolling pin (belan)."
  },
  {
    "slug": "brown-cutlery-set-4",
    "name": "Brown Cutlery Set (4 pcs)",
    "cost": 57,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/8/EX/AU/YB/37510322/product-jpeg-250x250.jpg",
    "dimensions": "4 pieces · Boxed",
    "desc": "Four-piece wooden cutlery set. Everyday use."
  },
  {
    "slug": "brown-cutlery-set",
    "name": "Brown Wooden Cutlery Set",
    "cost": 60,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "kitchen",
    "categoryLabel": "Kitchen & Dining",
    "image": "https://4.imimg.com/data4/HO/MO/ANDROID-37510322/product-250x250.jpeg",
    "dimensions": "Multi-size",
    "desc": "Wooden cutlery set in multiple sizes."
  },
  {
    "slug": "small-lamp",
    "name": "Pyramid Table Lamp",
    "cost": 700,
    "price": 1499,
    "mrp": 2299,
    "discount": 35,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/small-lamp.jpg",
    "dimensions": "Sheesham · Warm glow",
    "desc": "ExclusiveLane Sheesham wooden 'Pyramid' table lamp. Warm ambient glow."
  },
  {
    "slug": "wall-stands-set-3",
    "name": "Wall Stands (Set of 3)",
    "cost": 650,
    "price": 1399,
    "mrp": 2099,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/wall-stands-set-of-3.jpg",
    "dimensions": "Set of 3",
    "desc": "Wall shelf set of 3 for photos & decorations."
  },
  {
    "slug": "planters-decorative",
    "name": "Wooden Planter — Decorative Stand",
    "cost": 600,
    "price": 1299,
    "mrp": 1999,
    "discount": 35,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/planters.jpg",
    "dimensions": "Sheesham · 3-tier",
    "desc": "Modern wooden decorative planter stand rack for indoor / outdoor pots."
  },
  {
    "slug": "bagula-set",
    "name": "Bagula Set — Brass Antique Cranes",
    "cost": 600,
    "price": 1299,
    "mrp": 1999,
    "discount": 35,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/bagula-set.jpg",
    "dimensions": "Wood + Brass · Pair",
    "desc": "Wooden & brass antique decorative saras (cranes). Pair."
  },
  {
    "slug": "wall-shelf-rustic",
    "name": "Wall Shelf — Metal Rustic",
    "cost": 500,
    "price": 1099,
    "mrp": 1699,
    "discount": 35,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/wall-shelf.jpg",
    "dimensions": "Wood + Metal",
    "desc": "Wooden wall shelf with metallic black rustic mounts. Living room / bedroom."
  },
  {
    "slug": "wooden-bangle-holder",
    "name": "Wooden Bangle Holder",
    "cost": 285,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/GG/SJ/CT/37510322/new-product-250x250.jpeg",
    "dimensions": "27×11×30 cm",
    "desc": "Printed wooden bangle stand. Modern décor."
  },
  {
    "slug": "remote-stand-multi",
    "name": "Remote Stand — Multi-Purpose Carved",
    "cost": 280,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/remote-stand.jpg",
    "dimensions": "Sheesham · Carved",
    "desc": "Handmade multi-purpose wooden TV remote / desk supplies organiser."
  },
  {
    "slug": "dhoopdani-lobandan",
    "name": "Dhoopdani / Lobandan Pyramid",
    "cost": 280,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/dhoopdani-lobandan.jpg",
    "dimensions": "Sheesham · Pyramid",
    "desc": "Dhoop / loban incense holder with ash catcher. Traditional pyramid design."
  },
  {
    "slug": "tissue-box-brass",
    "name": "Tissue Box — Brass Inlay",
    "cost": 320,
    "price": 699,
    "mrp": 1049,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/tissue-box.jpg",
    "dimensions": "Sheesham · Brass",
    "desc": "Wooden tissue paper box with brass inlay. Car / home / office."
  },
  {
    "slug": "wall-bracket-floating",
    "name": "Wall Bracket — Floating Shelf",
    "cost": 270,
    "price": 649,
    "mrp": 999,
    "discount": 35,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/wall-bracket.jpg",
    "dimensions": "Single piece",
    "desc": "Wall shelf display floating hanging shelf. Single piece."
  },
  {
    "slug": "specs-stand-couple-set",
    "name": "Spectacle Stand — Couple Set",
    "cost": 250,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/specs-stand-couple-set.jpg",
    "dimensions": "Pair · Sheesham",
    "desc": "Wooden nose-shape couple set spectacle, goggles & sunglasses stand. His & Hers décor."
  },
  {
    "slug": "paper-weight-pen-stand",
    "name": "Paper Weight & Pen Stand",
    "cost": 230,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/paper-weight-and-pen-stand.jpg",
    "dimensions": "Sheesham · Cube",
    "desc": "Wooden cube-shape pen / pencil holder. Doubles as paper weight & desk organiser."
  },
  {
    "slug": "door-bell-brass",
    "name": "Door Bell — Brass Bell",
    "cost": 250,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/door-bell.jpg",
    "dimensions": "Wood + Brass",
    "desc": "Wall hanging door bell with brass bell. Hand-carved frame."
  },
  {
    "slug": "sindoor-dibbi-pair",
    "name": "Sindoor Dibbi (Pair)",
    "cost": 220,
    "price": 549,
    "mrp": 849,
    "discount": 35,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/sindoor-dibbi.jpg",
    "dimensions": "Pair · Carved",
    "desc": "CraftsCollectionStore wooden sindoor / kumkum / shringar box, hand-carved (set of 2)."
  },
  {
    "slug": "wooden-tissue-holder-7",
    "name": "Wooden Tissue Holder — 7\"",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/QL/BQ/ST/37510322/new-product-250x250.jpeg",
    "dimensions": "7 inch · Wood + Steel",
    "desc": "Tabletop tissue holder. Wood + mild steel finish."
  },
  {
    "slug": "mobile-stand-folded-hands",
    "name": "Mobile Stand — Folded Hands",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/mobile-stand-folded-hands.jpg",
    "dimensions": "Sheesham · Carved",
    "desc": "Stylish wooden mobile stand cum table décor in folded-hands design."
  },
  {
    "slug": "agarbatti-stand",
    "name": "Agarbatti Stand — Soulveda Cycle",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/agarbatti-stand.jpg",
    "dimensions": "Sheesham · Brass",
    "desc": "Pure wooden agarbatti stand with brass-bell cycle design and ash catcher."
  },
  {
    "slug": "ash-tray-carved",
    "name": "Ash Tray — Round Carved",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/ash-tray.jpg",
    "dimensions": "Sheesham · Round",
    "desc": "Hand-carved round wooden ash tray. For home, office, car."
  },
  {
    "slug": "sheesham-key-hangers",
    "name": "Sheesham Key Hangers (Set of 3)",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/sheesham-key-hangers.jpg",
    "dimensions": "Set of 3",
    "desc": "Stylish key hangers / holders for wall. Carved sheesham, set of 3."
  },
  {
    "slug": "designer-pen-stand",
    "name": "Designer Pen Stand",
    "cost": 170,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HH/ZL/IB/37510322/new-product-250x250.jpeg",
    "dimensions": "Boxed",
    "desc": "Designer wooden pen stand. Handcraft finish."
  },
  {
    "slug": "wooden-remote-stand",
    "name": "Wooden Remote Stand",
    "cost": 180,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/KI/JE/WJ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "9×17×20 cm · 4 shelves",
    "desc": "4-shelf wooden remote / desk organiser."
  },
  {
    "slug": "wooden-laptop-stand",
    "name": "Wooden Laptop Stand",
    "cost": 145,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/VS/LY/GL/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Foldable",
    "desc": "Portable foldable wooden laptop stand."
  },
  {
    "slug": "mobile-stand-floral",
    "name": "Mobile Stand — Floral Carved",
    "cost": 150,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/mobile-stand.jpg",
    "dimensions": "Sheesham · Carved",
    "desc": "Wooden single-cell phone stand with hand-carved floral motifs."
  },
  {
    "slug": "spec-stand-baby",
    "name": "Spectacle Stand — Baby Duck",
    "cost": 130,
    "price": 349,
    "mrp": 549,
    "discount": 36,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/spec-stand-baby.jpg",
    "dimensions": "Sheesham · Cute",
    "desc": "Cartoon duck-shaped spec stand for kids. Carved sheesham wood."
  },
  {
    "slug": "wooden-tissue-holder-15cm",
    "name": "Wooden Tissue Holder — Compact",
    "cost": 100,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/TJ/PA/ZN/37510322/new-product-250x250.jpeg",
    "dimensions": "15×6 cm",
    "desc": "Compact wooden tissue holder. Boxed."
  },
  {
    "slug": "wooden-incense-holder",
    "name": "Wooden Incense Holder",
    "cost": 95,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/AU/EN/MM/37510322/new-product-250x250.jpeg",
    "dimensions": "10×10×31 cm",
    "desc": "Tall wooden incense (agarbatti) holder."
  },
  {
    "slug": "brown-incense-holder",
    "name": "Brown Incense Holder",
    "cost": 88,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/LR/IX/KE/37510322/new-product-250x250.jpeg",
    "dimensions": "12×12×31 cm",
    "desc": "Brown wooden incense holder. Wider base."
  },
  {
    "slug": "incense-stick-holder",
    "name": "Incense Stick Holder",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/GY/RE/MA/37510322/new-product-250x250.jpeg",
    "dimensions": "14×14×30 cm",
    "desc": "Wide-base wooden incense stick holder."
  },
  {
    "slug": "key-rings-pair",
    "name": "Wooden Key Rings (Pair)",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "/key-rings.jpg",
    "dimensions": "Pair · Sheesham",
    "desc": "Sturdy hand-carved key rings for car & bikes. Sold as pair."
  },
  {
    "slug": "wooden-rehal-stand",
    "name": "Wooden Rehal Book Stand",
    "cost": 65,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/CC/KS/LK/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "8 inch · Matt",
    "desc": "Foldable wooden book stand (rehal). 5mm thick."
  },
  {
    "slug": "wooden-pen-stand",
    "name": "Wooden Pen Stand",
    "cost": 60,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "decor",
    "categoryLabel": "Home Décor",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/RX/KC/PP/37510322/new-product-250x250.jpeg",
    "dimensions": "Boxed",
    "desc": "Classic wooden pen stand. Desk essential."
  },
  {
    "slug": "wooden-wine-box",
    "name": "Wooden Wine Box",
    "cost": 550,
    "price": 1199,
    "mrp": 1799,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/PE/DS/HS/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "15×6×3 inch",
    "desc": "Premium wooden wine box. 5kg capacity, gift-ready."
  },
  {
    "slug": "wooden-rehal-box",
    "name": "Wooden Rehal Box",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/ANDROID/Default/2020/11/MX/BY/RH/37510322/product-jpeg-250x250.jpg",
    "dimensions": "Matt finish",
    "desc": "Traditional rehal box for the Holy book."
  },
  {
    "slug": "handcrafted-wooden-box",
    "name": "Handcrafted Wooden Box (Set)",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HO/YM/UI/37510322/new-product-250x250.jpeg",
    "dimensions": "8×5 / 7×5 / 6×4 inch",
    "desc": "Set of hand-carved nesting boxes — three sizes."
  },
  {
    "slug": "hand-carved-wooden-box",
    "name": "Hand Carved Wooden Box",
    "cost": 350,
    "price": 799,
    "mrp": 1199,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HQ/JW/OT/37510322/new-product-250x250.jpeg",
    "dimensions": "Handmade",
    "desc": "Intricately hand-carved wooden box. Heirloom quality."
  },
  {
    "slug": "square-jewelry-box",
    "name": "Square Wooden Jewelry Box",
    "cost": 175,
    "price": 449,
    "mrp": 699,
    "discount": 36,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/EW/CE/MI/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "6×6×2 inch",
    "desc": "Square jewellery storage box. 5mm thick walls."
  },
  {
    "slug": "designer-wooden-coin-box",
    "name": "Designer Wooden Coin Box",
    "cost": 140,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/GLADMIN/Default/2020/11/JS/KA/QF/37510322/new-product-250x250.jpeg",
    "dimensions": "Matt finish",
    "desc": "Designer hand-carved coin box. 500g, premium feel."
  },
  {
    "slug": "bottle-shape-coin-box",
    "name": "Bottle Shape Coin Box",
    "cost": 140,
    "price": 399,
    "mrp": 599,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/GLADMIN/Default/2020/11/BH/MX/SG/37510322/new-product-250x250.jpeg",
    "dimensions": "9×4×4 inch",
    "desc": "Unique bottle-shaped wooden coin box. Conversation piece."
  },
  {
    "slug": "wooden-money-box",
    "name": "Wooden Money Box",
    "cost": 110,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/KL/TY/SX/37510322/new-product-250x250.jpeg",
    "dimensions": "6×4 inch",
    "desc": "Rectangular wooden money savings box. Perfect gift for kids."
  },
  {
    "slug": "wooden-money-bank-box",
    "name": "Wooden Money Bank Box (Lockable)",
    "cost": 110,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/AJ/HQ/GV/37510322/new-product-250x250.jpeg",
    "dimensions": "Modern",
    "desc": "Lockable modern wooden money bank — keepsake quality."
  },
  {
    "slug": "modern-wooden-money-bank-box",
    "name": "Modern Money Bank — Round",
    "cost": 110,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/YH/YL/QT/37510322/new-product-250x250.jpeg",
    "dimensions": "4×5 inch · Round",
    "desc": "Round-shaped wooden money bank with modern finish."
  },
  {
    "slug": "wooden-coin-boxes",
    "name": "Wooden Coin Box — Square",
    "cost": 90,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/YB/RH/DT/37510322/new-product-250x250.jpeg",
    "dimensions": "4×4×4 inch",
    "desc": "Square wooden coin storage box. Hand-finished sheesham."
  },
  {
    "slug": "wooden-incense-box",
    "name": "Wooden Incense Box",
    "cost": 85,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/VD/PA/NY/37510322/new-product-250x250.jpeg",
    "dimensions": "3.5×3.5×7 inch",
    "desc": "Matt-finish wooden incense storage box."
  },
  {
    "slug": "rectangle-incense-box",
    "name": "Rectangle Incense Box",
    "cost": 95,
    "price": 299,
    "mrp": 449,
    "discount": 33,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/AX/SY/GQ/37510322/new-product-250x250.jpeg",
    "dimensions": "10.75″×2.5″×1.75″",
    "desc": "Rectangle wooden incense box."
  },
  {
    "slug": "designer-money-bank-box",
    "name": "Designer Money Bank Box",
    "cost": 75,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/HS/NN/BG/37510322/new-product-250x250.jpeg",
    "dimensions": "12×15×9 cm",
    "desc": "Compact designer money bank with modern appeal."
  },
  {
    "slug": "wooden-incense-stick-box",
    "name": "Incense Stick Storage Box",
    "cost": 75,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/IE/TU/DI/37510322/new-product-250x250.jpeg",
    "dimensions": "30×5.5×6.2 cm",
    "desc": "Long box for incense sticks (agarbatti). AH0378."
  },
  {
    "slug": "incense-stick-box-modern",
    "name": "Modern Incense Stick Box",
    "cost": 75,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/WI/NY/YG/37510322/new-product-250x250.jpeg",
    "dimensions": "30×5.5×6.5 cm",
    "desc": "Modern wooden incense stick box."
  },
  {
    "slug": "wooden-incense-box-25cm",
    "name": "Compact Incense Box",
    "cost": 70,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "boxes",
    "categoryLabel": "Boxes & Storage",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/RX/HC/ET/37510322/new-product-250x250.jpeg",
    "dimensions": "25×4.5×5 cm",
    "desc": "Compact wooden incense storage box."
  },
  {
    "slug": "playing-card-box-carved",
    "name": "Playing Card Box — Carved",
    "cost": 270,
    "price": 649,
    "mrp": 999,
    "discount": 35,
    "category": "games",
    "categoryLabel": "Games",
    "image": "/playing-card-box.jpg",
    "dimensions": "Carved · Sheesham",
    "desc": "Hand-carved single-deck card storage case. Tash card holder."
  },
  {
    "slug": "tic-tac-toe-with-box",
    "name": "Tic Tac Toe — With Storage Box",
    "cost": 250,
    "price": 599,
    "mrp": 899,
    "discount": 33,
    "category": "games",
    "categoryLabel": "Games",
    "image": "/tic-tac-toe-game-with-box.jpg",
    "dimensions": "Carved box · Sheesham",
    "desc": "Classic Tic Tac Toe Zero & Cross game in wooden storage box."
  },
  {
    "slug": "tic-tac-toe-open",
    "name": "Tic Tac Toe — Open Board",
    "cost": 200,
    "price": 499,
    "mrp": 749,
    "discount": 33,
    "category": "games",
    "categoryLabel": "Games",
    "image": "/tic-tac-toe-game.jpg",
    "dimensions": "Open board · Wood",
    "desc": "Classic Zero & Cross wooden Tic Tac Toe game (open board)."
  },
  {
    "slug": "wooden-foot-roller",
    "name": "Wooden Foot Roller",
    "cost": 45,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/ZS/II/DP/37510322/new-product-250x250.jpeg",
    "dimensions": "Foot relief",
    "desc": "Wooden foot massage roller. Stress relief."
  },
  {
    "slug": "wooden-massage-roller",
    "name": "Wooden Massage Roller",
    "cost": 65,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/CV/ZL/EO/37510322/new-product-250x250.jpeg",
    "dimensions": "All-purpose",
    "desc": "Wooden massage roller for body."
  },
  {
    "slug": "wooden-body-massage-roller",
    "name": "Wooden Body Massage Roller",
    "cost": 40,
    "price": 249,
    "mrp": 399,
    "discount": 38,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/SELLER/Default/2020/11/NG/CW/JI/37510322/new-product-250x250.jpeg",
    "dimensions": "Body relief",
    "desc": "Compact wooden body massage roller."
  },
  {
    "slug": "shoes-wearing-stick",
    "name": "Shoe Horn — Wooden Stick",
    "cost": 35,
    "price": 199,
    "mrp": 299,
    "discount": 33,
    "category": "wellness",
    "categoryLabel": "Wellness",
    "image": "https://5.imimg.com/data5/QG/YH/QZ/ANDROID-37510322/product-jpeg-250x250.jpg",
    "dimensions": "Long handle",
    "desc": "Long-handle wooden shoe horn / wearing stick."
  },
  {
    "slug": "coffee-tray-stand",
    "name": "Coffee Tray Stand — Premium",
    "cost": 2500,
    "price": 4599,
    "mrp": 6899,
    "discount": 33,
    "category": "furniture",
    "categoryLabel": "Statement Pieces",
    "image": "https://5.imimg.com/data5/GLADMIN/Default/2021/1/BY/LW/BH/37510322/coffee-tray-stand-250x250.jpg",
    "dimensions": "Premium",
    "desc": "Premium coffee tray stand. Statement piece."
  },
  {
    "slug": "atwas-table-carved",
    "name": "Atwas Table — Carved Round",
    "cost": 1300,
    "price": 2499,
    "mrp": 3799,
    "discount": 34,
    "category": "furniture",
    "categoryLabel": "Statement Pieces",
    "image": "/atwas-table.jpg",
    "dimensions": "Round carved · Sheesham",
    "desc": "Handmade wooden natural-brown carved table."
  },
  {
    "slug": "folding-side-table",
    "name": "Folding Side Table — Round",
    "cost": 1100,
    "price": 2099,
    "mrp": 3199,
    "discount": 34,
    "category": "furniture",
    "categoryLabel": "Statement Pieces",
    "image": "/folding-table.jpg",
    "dimensions": "Folding · Sheesham",
    "desc": "Hand-crafted folding side stool for living room / office. Lamp / books / vase stand."
  }
];

const inr = (n) => '₹' + n.toLocaleString('en-IN');
